# Generated by Django 5.1 on 2024-10-08 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_faculty_specialty_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.university'),
        ),
    ]
