# Generated by Django 5.1 on 2024-10-08 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_faculty_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.specialty'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.faculty'),
        ),
    ]
