# Generated by Django 5.1 on 2024-11-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_group_specialty_specialty_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(null=True, upload_to='students', verbose_name='Изображение'),
        ),
    ]
