# Generated by Django 5.1 on 2024-11-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='picture',
            field=models.ImageField(null=True, upload_to='universities', verbose_name='Изображение'),
        ),
    ]
